### ISSUE TITLE
My site is not a template for reuse

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [tunganhtran/tunganhtran.github.io#9]
Again, as I told you in the fork you deleted, [my README is very clear about this](https://github.com/AleksandrHovhannisyan/aleksandrhovhannisyan.com/#licensing):

> This repository is not a template for reuse and has no open-source license, but I'm hosting it publicly as a learning experience. It also [doubles as my comment system](https://www.aleksandrhovhannisyan.com/blog/static-site-comments-github-issues/). Unless otherwise noted, all rights are reserved (copyright Aleksandr Hovhannisyan 2019–Present).

>
> You are more than welcome to fork/clone this repo and explore the code. However, you may not redistribute any content that I own in this repo without my permission, unless I've already attributed it to someone else. When in doubt, please feel free to message me and ask!

Please remove all of my files/directories/code from this repo and create your own website; this is a substantial reproduction of my site content. You may find the template I linked to in my README useful if you want to create your own website, but you may _not_ clone someone else's site and make modifications to make it your own. Just because a site is on GitHub doesn't mean that it's not copyrighted. [Read the GitHub Terms of Service carefully](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#3-ownership-of-content-right-to-post-and-license-grants); you are currently violating their TOS and infringing on my copyright:

> You retain ownership of and responsibility for Your Content. If you're posting anything you did not create yourself or do not own the rights to, you agree that you are responsible for any Content you post; that you will only submit Content that you have the right to post; and that you will fully comply with any third party licenses relating to Content you post.

**Comment by tunganhtran** [comment]
OK! I will delete this repo
